[build]
  command = "echo 'Nenhum comando de build necessário'"
  publish = "/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
